### ISSUE TITLE
Site returns 500 error

### ISSUE THREAD

**Issue by namiarj** [psychonautwiki/plebis-indexer#1]
For some inputs plebis return error no 500.

https://pleb.is/query?q=%2B%2B+stage
https://pleb.is/query?q=god+%21

**Comment by 19h** [comment]
at least it doesn't burn

**Comment by 19h** [comment]
![post-40995-wolf-of-wall-street-nanny-cam-esov](https://user-images.githubusercontent.com/280212/40322727-95184b46-5d33-11e8-9ba1-2485ed5018ac.gif)

tbf it's probably a bug in the underlying fulltext search engine I'm using in the Rust component. I'll get rid of it somewhere soon and also replace Mongo with ElasticSearch, that should make the search less immobile.
